/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Socket */

#ifndef _Included_main_Socket
#define _Included_main_Socket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Socket
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_main_Socket_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_Socket
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Socket_deinit
  (JNIEnv *, jclass);

/*
 * Class:     main_Socket
 * Method:    sendTo
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_main_Socket_sendTo
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     main_Socket
 * Method:    recvFrom
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_main_Socket_recvFrom
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
